{
  "data": [
    [
      "1",
      "<img src='vistas/img/productos/101/105.png' width='40px'>",
      "101",
      "Aspiradora Industrial ",
      "Taladros",
      "20",
      "$1500",
      "$2100",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "2",
      "<img src='vistas/img/productos/102/940.jpg' width='40px'>",
      "102",
      "Plato Flotante para Allanadora",
      "Taladros",
      "20",
      "$4500",
      "$6300",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "3",
      "<img src='vistas/img/productos/103/763.jpg' width='40px'>",
      "103",
      "Compresor de Aire para pintura",
      "Taladros",
      "20",
      "$3000",
      "$4200",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "4",
      "<img src='vistas/img/productos/104/957.jpg' width='40px'>",
      "104",
      "Cortadora de Adobe sin Disco ",
      "Taladros",
      "20",
      "$4000",
      "$5600",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "5",
      "<img src='vistas/img/productos/105/630.jpg' width='40px'>",
      "105",
      "Cortadora de Piso sin Disco ",
      "Taladros",
      "20",
      "$1540",
      "$2156",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "6",
      "<img src='vistas/img/productos/106/635.jpg' width='40px'>",
      "106",
      "Disco Punta Diamante ",
      "Taladros",
      "20",
      "$1100",
      "$1540",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "7",
      "<img src='vistas/img/productos/107/848.jpg' width='40px'>",
      "107",
      "Extractor de Aire ",
      "Taladros",
      "20",
      "$1540",
      "$2156",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "8",
      "<img src='vistas/img/productos/108/163.jpg' width='40px'>",
      "108",
      "Guada?adora ",
      "Taladros",
      "20",
      "$1540",
      "$2156",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "9",
      "<img src='vistas/img/productos/109/769.jpg' width='40px'>",
      "109",
      "Hidrolavadora El?ctrica ",
      "Taladros",
      "20",
      "$2600",
      "$3640",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "10",
      "<img src='vistas/img/productos/110/582.jpg' width='40px'>",
      "110",
      "Hidrolavadora Gasolina",
      "Taladros",
      "20",
      "$2210",
      "$3094",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "11",
      "<img src='vistas/img/productos/101/105.png' width='40px'>",
      "111",
      "Motobomba a Gasolina",
      "Taladros",
      "20",
      "$2860",
      "$4004",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "12",
      "<img src='vistas/img/productos/102/940.jpg' width='40px'>",
      "112",
      "Motobomba El?ctrica",
      "Taladros",
      "20",
      "$2400",
      "$3360",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "13",
      "<img src='vistas/img/productos/103/763.jpg' width='40px'>",
      "113",
      "Sierra Circular ",
      "Taladros",
      "20",
      "$1100",
      "$1540",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "14",
      "<img src='vistas/img/productos/104/957.jpg' width='40px'>",
      "114",
      "Disco de tugsteno para Sierra circular",
      "Taladros",
      "20",
      "$4500",
      "$6300",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "15",
      "<img src='vistas/img/productos/105/630.jpg' width='40px'>",
      "115",
      "Soldador Electrico ",
      "Taladros",
      "20",
      "$1980",
      "$2772",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "16",
      "<img src='vistas/img/productos/106/635.jpg' width='40px'>",
      "116",
      "Careta para Soldador",
      "Taladros",
      "20",
      "$4200",
      "$5880",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "17",
      "<img src='vistas/img/productos/107/848.jpg' width='40px'>",
      "117",
      "Torre de iluminacion ",
      "Taladros",
      "20",
      "$1800",
      "$2520",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "18",
      "<img src='vistas/img/productos/108/163.jpg' width='40px'>",
      "201",
      "Martillo Demoledor de Piso 110V",
      "Taladros",
      "20",
      "$5600",
      "$7840",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "19",
      "<img src='vistas/img/productos/109/769.jpg' width='40px'>",
      "202",
      "Muela o cincel martillo demoledor piso",
      "Taladros",
      "20",
      "$9600",
      "$13440",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "20",
      "<img src='vistas/img/productos/110/582.jpg' width='40px'>",
      "203",
      "Taladro Demoledor de muro 110V",
      "Taladros",
      "20",
      "$3850",
      "$5390",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "21",
      "<img src='vistas/img/productos/101/105.png' width='40px'>",
      "204",
      "Muela o cincel martillo demoledor muro",
      "Taladros",
      "20",
      "$9600",
      "$13440",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "22",
      "<img src='vistas/img/productos/102/940.jpg' width='40px'>",
      "205",
      "Taladro Percutor de 1/2"
      Madera y Metal ",
      "Taladros",
      "20",
      "$8000",
      "$11200",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "23",
      "<img src='vistas/img/productos/103/763.jpg' width='40px'>",
      "206",
      "Taladro Percutor SDS Plus 110V",
      "Taladros",
      "20",
      "$3900",
      "$5460",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "24",
      "<img src='vistas/img/productos/104/957.jpg' width='40px'>",
      "207",
      "Taladro Percutor SDS Max 110V (Mineria)",
      "Taladros",
      "20",
      "$4600",
      "$6440",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "25",
      "<img src='vistas/img/productos/105/630.jpg' width='40px'>",
      "301",
      "Andamio colgante",
      "Taladros",
      "20",
      "$1440",
      "$2016",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "26",
      "<img src='vistas/img/productos/106/635.jpg' width='40px'>",
      "302",
      "Distanciador andamio colgante",
      "Taladros",
      "20",
      "$1600",
      "$2240",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "27",
      "<img src='vistas/img/productos/107/848.jpg' width='40px'>",
      "303",
      "Marco andamio modular ",
      "Taladros",
      "20",
      "$900",
      "$1260",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "28",
      "<img src='vistas/img/productos/108/163.jpg' width='40px'>",
      "304",
      "Marco andamio tijera",
      "Taladros",
      "20",
      "$100",
      "$140",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "29",
      "<img src='vistas/img/productos/109/769.jpg' width='40px'>",
      "305",
      "Tijera para andamio",
      "Taladros",
      "20",
      "$162",
      "$226",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "30",
      "<img src='vistas/img/productos/110/582.jpg' width='40px'>",
      "306",
      "Escalera interna para andamio",
      "Taladros",
      "20",
      "$270",
      "$378",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "31",
      "<img src='vistas/img/productos/101/105.png' width='40px'>",
      "307",
      "Pasamanos de seguridad",
      "Taladros",
      "20",
      "$75",
      "$105",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "32",
      "<img src='vistas/img/productos/102/940.jpg' width='40px'>",
      "308",
      "Rueda giratoria para andamio",
      "Taladros",
      "20",
      "$168",
      "$235",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "33",
      "<img src='vistas/img/productos/103/763.jpg' width='40px'>",
      "309",
      "Arnes de seguridad",
      "Taladros",
      "20",
      "$1750",
      "$2450",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "34",
      "<img src='vistas/img/productos/104/957.jpg' width='40px'>",
      "310",
      "Eslinga para arnes",
      "Taladros",
      "20",
      "$175",
      "$245",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "35",
      "<img src='vistas/img/productos/105/630.jpg' width='40px'>",
      "311",
      "Plataforma Met?lica",
      "Taladros",
      "20",
      "$420",
      "$588",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "36",
      "<img src='vistas/img/productos/106/635.jpg' width='40px'>",
      "401",
      "Planta Electrica Diesel 6 Kva",
      "Taladros",
      "20",
      "$3500",
      "$4900",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "37",
      "<img src='vistas/img/productos/107/848.jpg' width='40px'>",
      "402",
      "Planta Electrica Diesel 10 Kva",
      "Taladros",
      "20",
      "$3550",
      "$4970",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "38",
      "<img src='vistas/img/productos/108/163.jpg' width='40px'>",
      "403",
      "Planta Electrica Diesel 20 Kva",
      "Taladros",
      "20",
      "$3600",
      "$5040",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "39",
      "<img src='vistas/img/productos/109/769.jpg' width='40px'>",
      "404",
      "Planta Electrica Diesel 30 Kva",
      "Taladros",
      "20",
      "$3650",
      "$5110",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "40",
      "<img src='vistas/img/productos/110/582.jpg' width='40px'>",
      "405",
      "Planta Electrica Diesel 60 Kva",
      "Taladros",
      "20",
      "$3700",
      "$5180",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "41",
      "<img src='vistas/img/productos/101/105.png' width='40px'>",
      "406",
      "Planta Electrica Diesel 75 Kva",
      "Taladros",
      "20",
      "$3750",
      "$5250",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "42",
      "<img src='vistas/img/productos/102/940.jpg' width='40px'>",
      "407",
      "Planta Electrica Diesel 100 Kva",
      "Taladros",
      "20",
      "$3800",
      "$5320",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "43",
      "<img src='vistas/img/productos/103/763.jpg' width='40px'>",
      "408",
      "Planta Electrica Diesel 120 Kva",
      "Taladros",
      "20",
      "$3850",
      "$5390",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "44",
      "<img src='vistas/img/productos/104/957.jpg' width='40px'>",
      "501",
      "Escalera de Tijera Aluminio ",
      "Taladros",
      "20",
      "$350",
      "$490",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "45",
      "<img src='vistas/img/productos/105/630.jpg' width='40px'>",
      "502",
      "Extension Electrica ",
      "Taladros",
      "20",
      "$370",
      "$518",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "46",
      "<img src='vistas/img/productos/106/635.jpg' width='40px'>",
      "503",
      "Gato tensor",
      "Taladros",
      "20",
      "$380",
      "$532",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "47",
      "<img src='vistas/img/productos/107/848.jpg' width='40px'>",
      "504",
      "Lamina Cubre Brecha ",
      "Taladros",
      "20",
      "$380",
      "$532",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "48",
      "<img src='vistas/img/productos/108/163.jpg' width='40px'>",
      "505",
      "Llave de Tubo",
      "Taladros",
      "20",
      "$480",
      "$672",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "49",
      "<img src='vistas/img/productos/109/769.jpg' width='40px'>",
      "506",
      "Manila por Metro",
      "Taladros",
      "20",
      "$600",
      "$840",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "50",
      "<img src='vistas/img/productos/110/582.jpg' width='40px'>",
      "507",
      "Polea 2 canales",
      "Taladros",
      "20",
      "$900",
      "$1260",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "51",
      "<img src='vistas/img/productos/101/105.png' width='40px'>",
      "508",
      "Tensor",
      "Taladros",
      "20",
      "$100",
      "$140",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "52",
      "<img src='vistas/img/productos/102/940.jpg' width='40px'>",
      "509",
      "Bascula ",
      "Taladros",
      "20",
      "$130",
      "$182",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "53",
      "<img src='vistas/img/productos/103/763.jpg' width='40px'>",
      "510",
      "Bomba Hidrostatica",
      "Taladros",
      "20",
      "$770",
      "$1078",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "54",
      "<img src='vistas/img/productos/104/957.jpg' width='40px'>",
      "511",
      "Chapeta",
      "Taladros",
      "20",
      "$660",
      "$924",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "55",
      "<img src='vistas/img/productos/105/630.jpg' width='40px'>",
      "512",
      "Cilindro muestra de concreto",
      "Taladros",
      "20",
      "$400",
      "$560",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "56",
      "<img src='vistas/img/productos/106/635.jpg' width='40px'>",
      "513",
      "Cizalla de Palanca",
      "Taladros",
      "20",
      "$450",
      "$630",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "57",
      "<img src='vistas/img/productos/107/848.jpg' width='40px'>",
      "514",
      "Cizalla de Tijera",
      "Taladros",
      "20",
      "$580",
      "$812",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "58",
      "<img src='vistas/img/productos/108/163.jpg' width='40px'>",
      "515",
      "Coche llanta neumatica",
      "Taladros",
      "20",
      "$420",
      "$588",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "59",
      "<img src='vistas/img/productos/109/769.jpg' width='40px'>",
      "516",
      "Cono slump",
      "Taladros",
      "20",
      "$140",
      "$196",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ],
    [
      "60",
      "<img src='vistas/img/productos/110/582.jpg' width='40px'>",
      "517",
      "Cortadora de Baldosin",
      "Taladros",
      "20",
      "$930",
      "$1302",
      "2018-08-22 22:38:21",
      "<div class='btn-group'><button class='btn btn-warning'><i class='fa fa-pencil'></i></button><button class='btn btn-danger'><i class='fa fa-times'></i></button></div>"
    ]
  ]
}